export const APP_NAME = Object.freeze({
  HOME: "SANDBOX_HOME",
  ROOM: "SANDBOX_ROOM"
})

export const RESOURECES_ACTION_TYPE = Object.freeze({
  COLLECTION_ADD: "COLLECTION_ADD",
  COLLECTION_MODIFY: "COLLECTION_MODIFY",
  COLLECTION_REMOVE: "COLLECTION_REMOVE",
  DOCUMENT_UPDATE: "DOCUMENT_UPDATE",
})
